export interface TMDBMedia {
  id: number;
  title: string;
  name?: string; // For TV shows
  poster_path: string | null;
  backdrop_path: string | null;
  vote_average: number;
  release_date?: string;
  first_air_date?: string; // For TV shows
  genre_ids: number[];
  overview: string;
  media_type: "movie" | "tv";
}

export const fallbackTrendingMovies: TMDBMedia[] = [
  {
    id: 693134,
    title: "Dune: Part Two",
    poster_path: "/czemb574OI8K1QJ5545tQ6BfHth.jpg",
    backdrop_path: "/xOMo8j3i032c2mq6jH6i0O0sEvA.jpg",
    vote_average: 8.3,
    release_date: "2024-02-27",
    genre_ids: [878, 12],
    overview: "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.",
    media_type: "movie",
  },
  {
    id: 872585,
    title: "Oppenheimer",
    poster_path: "/8Gxv2Z7HqD6hwN0jRcZ6kyiW7zS.jpg",
    backdrop_path: "/nb3xzh9n2BABUIIuW2vE8OIu67N.jpg",
    vote_average: 8.1,
    release_date: "2023-07-19",
    genre_ids: [18, 36],
    overview: "The story of J. Robert Oppenheimer's role in the Manhattan Project during World War II and the creation of the atomic bomb.",
    media_type: "movie",
  },
  {
    id: 157336,
    title: "Interstellar",
    poster_path: "/gEU2QvEOmfcFgawjJySy67J4nUI.jpg",
    backdrop_path: "/xJHokZbljvjADY58vxNu76Z86t5.jpg",
    vote_average: 8.4,
    release_date: "2014-11-05",
    genre_ids: [12, 18, 878],
    overview: "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel.",
    media_type: "movie",
  },
  {
    id: 569094,
    title: "Spider-Man: Across the Spider-Verse",
    poster_path: "/8Vt1tTTjLJjQTYI6maZ24407IVg.jpg",
    backdrop_path: "/tmU7GeKVZ2uOD5QJeeG7SeTM92L.jpg",
    vote_average: 8.4,
    release_date: "2023-05-31",
    genre_ids: [16, 28, 12, 878],
    overview: "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse.",
    media_type: "movie",
  },
  {
    id: 155,
    title: "The Dark Knight",
    poster_path: "/qJ2tWGBbe58mQC7Ev1P7sujQO30.jpg",
    backdrop_path: "/dqK7CMBFFA1xwgj6r6L1yL0d85S.jpg",
    vote_average: 8.5,
    release_date: "2008-07-16",
    genre_ids: [28, 80, 18, 53],
    overview: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations.",
    media_type: "movie",
  },
  {
    id: 129,
    title: "Spirited Away",
    poster_path: "/39wmItIWsg5sclJgTy6n2GGe5zC.jpg",
    backdrop_path: "/m4ISSt55ISU5v425H2cnPP1T8fs.jpg",
    vote_average: 8.5,
    release_date: "2001-07-20",
    genre_ids: [16, 14, 35],
    overview: "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free them.",
    media_type: "movie",
  },
  {
    id: 496243,
    title: "Parasite",
    poster_path: "/7IiTTzbZzb2Ywz4wzy9j36q6ex3.jpg",
    backdrop_path: "/hiKmA9qQCeeFM656qSiKRXfY28g.jpg",
    vote_average: 8.5,
    release_date: "2019-05-30",
    genre_ids: [35, 53, 18],
    overview: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    media_type: "movie",
  }
];

export const fallbackTrendingTV: TMDBMedia[] = [
  {
    id: 1396,
    title: "Breaking Bad",
    name: "Breaking Bad",
    poster_path: "/ztkUQv63U719bb6t36EBTy14J7J.jpg",
    backdrop_path: "/tsRy6QAaquEsLZghy67J6thNko0.jpg",
    vote_average: 8.9,
    first_air_date: "2008-01-20",
    genre_ids: [18, 80],
    overview: "Walter White, a New Mexico chemistry teacher, diagnosed with Stage III cancer, turns to manufacturing and selling methamphetamine with a former student, Jesse Pinkman, to secure his family's financial future.",
    media_type: "tv",
  },
  {
    id: 66732,
    title: "Stranger Things",
    name: "Stranger Things",
    poster_path: "/49W5x55vyFCabKSyJGaIQ8m24Ju.jpg",
    backdrop_path: "/56v2Kj2qLz36a3RM50Z6Z6g5t6S.jpg",
    vote_average: 8.6,
    first_air_date: "2016-07-15",
    genre_ids: [18, 10765, 9648],
    overview: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
    media_type: "tv",
  },
  {
    id: 1399,
    title: "Game of Thrones",
    name: "Game of Thrones",
    poster_path: "/1XS1oq12pu6k6Clj2LVZ679yCI4.jpg",
    backdrop_path: "/2OMG2BrqmH7vR4JjzyPa57e02e0.jpg",
    vote_average: 8.4,
    first_air_date: "2011-04-17",
    genre_ids: [10765, 18, 10759],
    overview: "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest North.",
    media_type: "tv",
  },
  {
    id: 95396,
    title: "Severance",
    name: "Severance",
    poster_path: "/qm9U8p9gU2451C8407Jd693S850.jpg",
    backdrop_path: "/2k6g6Z2XQj6sXmY6Wn3D8n0d1Jg.jpg",
    vote_average: 8.4,
    first_air_date: "2022-02-17",
    genre_ids: [18, 9648, 878],
    overview: "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears outside of work, it begins a journey to discover the truth about their jobs.",
    media_type: "tv",
  },
  {
    id: 87108,
    title: "Chernobyl",
    name: "Chernobyl",
    poster_path: "/hlLXt2t76zxJgKPNlhptzOCS4tA.jpg",
    backdrop_path: "/uM2v8DqRj9Y3C6Sj87O92Jt79OQ.jpg",
    vote_average: 8.6,
    first_air_date: "2019-05-06",
    genre_ids: [18],
    overview: "The true story of one of the worst man-made catastrophes in history: the April 1986 nuclear power plant explosion in Ukraine. From the perspective of the brave souls who worked to save Europe from disaster.",
    media_type: "tv",
  },
  {
    id: 94605,
    title: "Arcane",
    name: "Arcane",
    poster_path: "/c55L0tPg7q6j5gS6gP1aX7gR2S.jpg",
    backdrop_path: "/fqWZ6Qf4yQ97O39g2C5X7jS9Z6L.jpg",
    vote_average: 8.7,
    first_air_date: "2021-11-06",
    genre_ids: [16, 10759, 10765, 18],
    overview: "Amidst the escalating discord between the rich, utopian city of Piltover and the seedy, oppressed underground of Zaun, two sisters fight on opposite sides of a war.",
    media_type: "tv",
  }
];

export const fallbackTollywood: TMDBMedia[] = [
  {
    id: 579974,
    title: "RRR",
    poster_path: "/wdrCwjR5x5NmFY5rwv45zpbz7C8.jpg",
    backdrop_path: "/n5K9UU4kaAd641ry5iO4xd25OiT.jpg",
    vote_average: 7.8,
    release_date: "2022-03-24",
    genre_ids: [28, 18, 36],
    overview: "A fictional history of two legendary revolutionaries' journey away from home before they began fighting for their country in the 1920s.",
    media_type: "movie",
  },
  {
    id: 1010818,
    title: "Kalki 2898 AD",
    poster_path: "/9m161Gv12gTcvu4bV3sHq39A86p.jpg",
    backdrop_path: "/oV4ZQQz9gB3zGkQ9sN0fK4KxN8L.jpg",
    vote_average: 7.2,
    release_date: "2024-06-27",
    genre_ids: [878, 28, 12],
    overview: "A modern avatar of Vishnu, a Hindu god, is believed to have descended to earth to protect the world from evil forces in a post-apocalyptic future.",
    media_type: "movie",
  },
  {
    id: 347201,
    title: "Baahubali: The Beginning",
    poster_path: "/97Ozb5G9OfHw73Z5VF4UptnEvuz.jpg",
    backdrop_path: "/7k7p2q0s270Xhp9i8I1jHL5m.jpg",
    vote_average: 7.6,
    release_date: "2015-07-10",
    genre_ids: [28, 12, 18, 14],
    overview: "In the kingdom of Mahishmati, while pursuing his love, a young man learns of his true heritage, family feud and his duty to overthrow the tyrant king.",
    media_type: "movie",
  },
  {
    id: 453181,
    title: "Baahubali 2: The Conclusion",
    poster_path: "/wFwL63l0EofLqXJlhL4wQn8k8j7.jpg",
    backdrop_path: "/2XWqG953966sXmY6Wn3D8n0d1Jg.jpg",
    vote_average: 7.8,
    release_date: "2017-04-27",
    genre_ids: [28, 12, 14, 18],
    overview: "When Shiva, the son of Bahubali, learns about his heritage, he begins to look for answers. His story is juxtaposed with past events in the Mahishmati Kingdom.",
    media_type: "movie",
  },
  {
    id: 695721,
    title: "Pushpa: The Rise",
    poster_path: "/p9O5b5G9OfHw73Z5VF4UptnEvuz.jpg",
    backdrop_path: "/sd4X0Kn22t702aC06a5UjH7t0OQ.jpg",
    vote_average: 7.4,
    release_date: "2021-12-16",
    genre_ids: [28, 18, 80],
    overview: "Pushpa Raj, a coolie, rises in the world of red sandalwood smuggling, making enemies along the way who try to bring him down.",
    media_type: "movie",
  }
];

export const fallbackKollywood: TMDBMedia[] = [
  {
    id: 868421,
    title: "Vikram",
    poster_path: "/dmZ9114bJ8Gxv2Z7HqD6hwN0jRc.jpg",
    backdrop_path: "/sd4X0Kn22t702aC06a5UjH7t0OQ.jpg",
    vote_average: 7.7,
    release_date: "2022-06-03",
    genre_ids: [28, 53, 80],
    overview: "A special ops team is summoned to investigate a series of mysterious killings by a group of masked vigilantes.",
    media_type: "movie",
  },
  {
    id: 1073125,
    title: "Leo",
    poster_path: "/l9f7114bJ8Gxv2Z7HqD6hwN0jRc.jpg",
    backdrop_path: "/2k6g6Z2XQj6sXmY6Wn3D8n0d1Jg.jpg",
    vote_average: 7.3,
    release_date: "2023-10-18",
    genre_ids: [28, 80, 53],
    overview: "A mild-mannered cafe owner becomes a local hero, but old ties return to haunt him, demanding his return to the gangland.",
    media_type: "movie",
  },
  {
    id: 638131,
    title: "Kaithi",
    poster_path: "/8pf7114bJ8Gxv2Z7HqD6hwN0jRc.jpg",
    backdrop_path: "/sd4X0Kn22t702aC06a5UjH7t0OQ.jpg",
    vote_average: 8.1,
    release_date: "2019-10-25",
    genre_ids: [28, 53, 80],
    overview: "A prisoner in transit is recruited by a police officer to drive a truck full of poisoned cops to the hospital in exchange for seeing his daughter.",
    media_type: "movie",
  },
  {
    id: 1008005,
    title: "Jailer",
    poster_path: "/2p8O5b5G9OfHw73Z5VF4UptnEvuz.jpg",
    backdrop_path: "/77x9p2q0s270Xhp9i8I1jHL5m.jpg",
    vote_average: 7.2,
    release_date: "2023-08-10",
    genre_ids: [28, 35, 80],
    overview: "A retired jailer goes on a manhunt to find his son's killers, but his dark past is slowly revealed as he uses his old connections.",
    media_type: "movie",
  }
];

export const fallbackMollywood: TMDBMedia[] = [
  {
    id: 1216221,
    title: "Manjummel Boys",
    poster_path: "/gD49W5x55vyFCabKSyJGaIQ8m24Ju.jpg",
    backdrop_path: "/sd4X0Kn22t702aC06a5UjH7t0OQ.jpg",
    vote_average: 8.0,
    release_date: "2024-02-22",
    genre_ids: [18, 12, 53],
    overview: "A group of friends from a small town in Kerala go on a trip to Kodaikanal, but their holiday turns into a rescue mission in the Guna Caves.",
    media_type: "movie",
  },
  {
    id: 1243165,
    title: "Premalu",
    poster_path: "/e94560f76zxJgKPNlhptzOCS4tA.jpg",
    backdrop_path: "/2k6g6Z2XQj6sXmY6Wn3D8n0d1Jg.jpg",
    vote_average: 7.9,
    release_date: "2024-02-09",
    genre_ids: [35, 10749],
    overview: "Sachin pursues romance in Hyderabad, leading to funny situations and misunderstandings with Reenu.",
    media_type: "movie",
  },
  {
    id: 1249332,
    title: "Aavesham",
    poster_path: "/2p8O5b5G9OfHw73Z5VF4UptnEvuz.jpg",
    backdrop_path: "/77x9p2q0s270Xhp9i8I1jHL5m.jpg",
    vote_average: 8.2,
    release_date: "2024-04-11",
    genre_ids: [35, 28],
    overview: "Three college students in Bangalore seek the help of a local gangster, Ranga, to take revenge on their seniors who bullied them.",
    media_type: "movie",
  },
  {
    id: 242095,
    title: "Drishyam",
    poster_path: "/hlLXt2t76zxJgKPNlhptzOCS4tA.jpg",
    backdrop_path: "/uM2v8DqRj9Y3C6Sj87O92Jt79OQ.jpg",
    vote_average: 8.4,
    release_date: "2013-12-19",
    genre_ids: [18, 53, 9648],
    overview: "A cable TV operator goes to extreme lengths to protect his family from a relentless police investigation after an accidental crime.",
    media_type: "movie",
  }
];

export const fallbackBollywood: TMDBMedia[] = [
  {
    id: 872906,
    title: "Jawan",
    poster_path: "/dmZ9114bJ8Gxv2Z7HqD6hwN0jRc.jpg",
    backdrop_path: "/sd4X0Kn22t702aC06a5UjH7t0OQ.jpg",
    vote_average: 7.2,
    release_date: "2023-09-07",
    genre_ids: [28, 53],
    overview: "A man is driven by a personal vendetta to rectify the wrongs in society, while keeping a promise made years ago.",
    media_type: "movie",
  },
  {
    id: 1042813,
    title: "Pathaan",
    poster_path: "/e94560f76zxJgKPNlhptzOCS4tA.jpg",
    backdrop_path: "/2k6g6Z2XQj6sXmY6Wn3D8n0d1Jg.jpg",
    vote_average: 6.8,
    release_date: "2023-01-25",
    genre_ids: [28, 12, 53],
    overview: "An Indian secret agent, Pathaan, comes out of hiding to stop a rogue mercenary group from destroying the nation.",
    media_type: "movie",
  },
  {
    id: 20453,
    title: "3 Idiots",
    poster_path: "/2p8O5b5G9OfHw73Z5VF4UptnEvuz.jpg",
    backdrop_path: "/77x9p2q0s270Xhp9i8I1jHL5m.jpg",
    vote_average: 8.0,
    release_date: "2009-12-23",
    genre_ids: [35, 18],
    overview: "Two friends search for their long-lost companion. They revisit their college days and recall their memories of their friend who inspired them to think differently.",
    media_type: "movie",
  },
  {
    id: 781732,
    title: "Animal",
    poster_path: "/p9O5b5G9OfHw73Z5VF4UptnEvuz.jpg",
    backdrop_path: "/sd4X0Kn22t702aC06a5UjH7t0OQ.jpg",
    vote_average: 6.5,
    release_date: "2023-12-01",
    genre_ids: [28, 18, 80],
    overview: "A son's obsessive love for his father leads him on a path of extreme violence and bloodshed against those who threaten his family.",
    media_type: "movie",
  }
];

export const fallbackAnime: TMDBMedia[] = [
  {
    id: 85937,
    title: "Demon Slayer: Kimetsu no Yaiba",
    name: "Demon Slayer",
    poster_path: "/xBHvZ22DG7ig36JRI4w6Spj4TE1.jpg",
    backdrop_path: "/nTvM0mh19tNHzVw7eJ264jEB7Tn.jpg",
    vote_average: 8.7,
    first_air_date: "2019-04-06",
    genre_ids: [16, 10759, 10765],
    overview: "A young boy, Tanjiro, sets out to become a demon slayer after his family is slaughtered and his sister is turned into a demon.",
    media_type: "tv",
  },
  {
    id: 1429,
    title: "Attack on Titan",
    name: "Attack on Titan",
    poster_path: "/hTP1DtmgSuUrjCdpt6Z2I6140oz.jpg",
    backdrop_path: "/7qGQLwQc3QW2oO3Cj42Z6QSu3o9.jpg",
    vote_average: 8.7,
    first_air_date: "2013-04-07",
    genre_ids: [16, 10759, 10765, 18],
    overview: "Humans fight for survival inside walled cities surrounded by giant man-eating humanoids called Titans.",
    media_type: "tv",
  },
  {
    id: 95479,
    title: "Jujutsu Kaisen",
    name: "Jujutsu Kaisen",
    poster_path: "/g1wW93966sXmY6Wn3D8n0d1Jg.jpg",
    backdrop_path: "/2XWqG953966sXmY6Wn3D8n0d1Jg.jpg",
    vote_average: 8.6,
    first_air_date: "2020-10-03",
    genre_ids: [16, 10759, 10765],
    overview: "A high school student swallows a cursed finger to save his friends, becoming the host of the King of Curses, Sukuna, and joins a secret school for Sorcerers.",
    media_type: "tv",
  },
  {
    id: 31917,
    title: "Naruto Shippuden",
    name: "Naruto Shippuden",
    poster_path: "/o622p4W7vVvS16pX0r7n3wG.jpg",
    backdrop_path: "/7qGQLwQc3QW2oO3Cj42Z6QSu3o9.jpg",
    vote_average: 8.6,
    first_air_date: "2007-02-15",
    genre_ids: [16, 10759, 10765],
    overview: "Naruto Uzumaki returns to the Leaf Village after years of training, ready to face the Akatsuki organization and bring his friend Sasuke home.",
    media_type: "tv",
  }
];

export const fallbackHiddenGems: TMDBMedia[] = [
  {
    id: 538804,
    title: "Tumbbad",
    poster_path: "/8X6zX0j6sXmY6Wn3D8n0d1Jg.jpg",
    backdrop_path: "/2k6g6Z2XQj6sXmY6Wn3D8n0d1Jg.jpg",
    vote_average: 8.2,
    release_date: "2018-10-12",
    genre_ids: [14, 27, 53, 18],
    overview: "A mythological story about a family who builds a shrine for Hastar, a monster god who should not be worshipped, and suffers the consequences of greed.",
    media_type: "movie",
  },
  {
    id: 1024546,
    title: "Kantara",
    poster_path: "/dmZ9114bJ8Gxv2Z7HqD6hwN0jRc.jpg",
    backdrop_path: "/sd4X0Kn22t702aC06a5UjH7t0OQ.jpg",
    vote_average: 8.0,
    release_date: "2022-09-30",
    genre_ids: [28, 12, 14, 18],
    overview: "A conflict between a forest officer and a rebel villager in a coastal town of Karnataka leads to an ancient battle between humans and spirits.",
    media_type: "movie",
  },
  {
    id: 569848,
    title: "Super Deluxe",
    poster_path: "/e94560f76zxJgKPNlhptzOCS4tA.jpg",
    backdrop_path: "/2k6g6Z2XQj6sXmY6Wn3D8n0d1Jg.jpg",
    vote_average: 8.1,
    release_date: "2019-03-29",
    genre_ids: [18, 35, 53],
    overview: "Four different stories of people in Chennai face their secrets and fears in a single day, leading to life-altering outcomes.",
    media_type: "movie",
  },
  {
    id: 521876,
    title: "C/o Kancharapalem",
    poster_path: "/p9O5b5G9OfHw73Z5VF4UptnEvuz.jpg",
    backdrop_path: "/77x9p2q0s270Xhp9i8I1jHL5m.jpg",
    vote_average: 8.3,
    release_date: "2018-09-07",
    genre_ids: [18, 35, 10749],
    overview: "Four unconventional love stories spanning across different ages, religions, and status in the small town of Kancharapalem.",
    media_type: "movie",
  }
];
